"""Initial migration.

Revision ID: d0c7b8e4b57c
Revises: 
Create Date: 2022-11-08 17:00:02.151921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c7b8e4b57c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topico', sa.Integer(), nullable=True),
    sa.Column('usuario', sa.String(length=30), nullable=True),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.Column('texto_review', sa.String(length=500), nullable=True),
    sa.Column('data_review', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topico'], ['topico.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('topico')
    # ### end Alembic commands ###